version: '3.4'

volumes:
  my_volume:
    driver: local

services:
  webapplication12:
    image: ${DOCKER_REGISTRY-}webapplication12
    build:
      context: .
      dockerfile: WebApplication12/Dockerfile
  mysql_server:
    image: mysql
    restart: always
    ports: 
    - "127.0.0.1:3306:3306"
    volumes:
      - my_volume:/datadir:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 